services:
  postgres:
    container_name: clinic_ecommerce_pg_sql
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - clinic-ecommerce-net
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5


  zipkin:
    image: openzipkin/zipkin:3
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - clinic-ecommerce-net
    restart: unless-stopped



networks:
  clinic-ecommerce-net:
    driver: bridge

volumes:
  postgres:

