services:
  postgres:
    container_name: clinic_ecommerce_pg_sql
    image : postgres:17-alpine
    environment:
      POSTGRES_USER : ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD : ${POSTGRES_PASSWORD:-password}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - clinic-ecommerce-net
    restart: unless-stopped

#  keycloak:
#    container_name: clinic_ecommerce_keycloak
#    image: quay.io/keycloak/keycloak:26.1.3
#    ports:
#      - ${KEYCLOAK_PORT:-9090}:8080
#    environment:
#      KC_DB: postgres
#      KC_DB_URL: jdbc:postgresql://host.docker.internal:5432/keycloak
#      KC_DB_USERNAME: ${POSTGRES_USER:-postgres}
#      KC_DB_PASSWORD: ${POSTGRES_PASSWORD:-password}
#      KC_HOSTNAME: localhost
#      KC_HEALTH_ENABLED: true # Enable health and metrics support
#      KC_METRICS_ENABLED: true
#      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
#      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
##      KC_HTTP_PORT: ${KEYCLOAK_PORT:-9090}
#      KC_HTTP_RELATIVE_PATH: /
#    command:
#      - "start-dev"
#      - --import-realm
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#    volumes:
#      - ./keycloak/:/opt/keycloak/data/import/
#    depends_on:
#      - postgres
#    networks:
#      - clinic-ecommerce-net
#    restart: unless-stopped


networks:
  clinic-ecommerce-net:
    driver: bridge

volumes:
  postgres:

