eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    config:
      override-system-properties: false

application:
  frontend:
    url: http://localhost:5173


#management:
#  tracing:
#    sampling:
#      probability: 1.0

