eureka:
#  instance:
#    hostname: ${EUREKA_HOSTNAME:localhost}
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

spring:
  cloud:
    config:
      override-system-properties: false


management:
  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: ${ZIPKIN_HOSTNAME:http://localhost:9411}/api/v2/spans

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

application:
  frontend:
    url: http://localhost:5173


#management:
#  tracing:
#    sampling:
#      probability: 1.0

