server:
  port: 9000

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/user}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

jwt:
  secret: ${JWT_SECRET:9e06f0619a02fb2b3e8f720f475f92deb5eaed07cf116145c29dba6e32596013a4be724b02018216d185b4a8bb114882}
  expiration: 86400000
  refresh-token:
    expiration: 86400000

